spring:
  application:
    name: product-service

#  sleuth:
#    sampler:
#      probability: 1.0  # 모든 요청에 대해 트레이스를 추적 (0.0 ~ 1.0 범위)
#    zipkin:
#      baseUrl: http://localhost:9411  # Zipkin 서버 URL 설정 (Zipkin 대시보드 서버)

  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



#server:
#  port: 19093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

